### ISSUE TITLE
Crash on iPad

### ISSUE THREAD

**Issue by jonathanwuki** [KaneCheshire/PreviewableActivityViewController#3]
When calling the share sheet on iPad, the app crashes. This is because it creates an action sheet which iPads don't use -- instead, popovers are used.

Here is the error message from Xcode console:

`In its current trait environment, the modalPresentationStyle of a PreviewableActivityViewController with this style is UIModalPresentationPopover. You must provide location information for this popover through the view controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the view controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'`

**Comment by insleep** [comment]
So, turns out it was an issue with the code on my side. Whooooooops...
